spring:
  application:
    name: Gamification
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    username: postgres
    password: 191130
    url: 'jdbc:postgresql://localhost:5432/quiz_edu'
    driver-class-name: org.postgresql.Driver
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
logging:
  level:
    org:
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: debug